# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[31,)" #mandatory (31 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/DavidM1A2/AstaraBot/issues"

# A list of mods
[[mods]]
# The modid of the mod
modId = "astarabot"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "1.0.0"
# A display name for the mod
displayName = "Astara Bot"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://www.curseforge.com/minecraft/mc-mods/astarabot/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "astarabot.png"
# A text field displayed in the mod UI
credits = "Mod created by David_M1A2 and namcap623."
# A text field displayed in the mod UI
authors = "David_M1A2 and namcap623"
# The description text for the mod (multi line!) (#mandatory)
description = '''
Bot for use on simplicitypvp.net
'''

# The first mod dependency is forge itself
[[dependencies.astarabot]] #optional
# the modid of the dependency
modId = "forge"
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true
# The version range of the dependency
versionRange = "[31,)"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"

# The second mod dependency is minecraft 1.15.2
[[dependencies.astarabot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"